SELECT TO_CHAR("START_TIME", 'HH24:MI:SS') AS "START_TIME",
       "COMMAND_NAME",
       "COMMAND_CLASS",
       CAST("DURATION" AS DOUBLE) AS "DURATION",
       CAST("CPU" AS DOUBLE) AS "CPU",
       "SUCCESS",
       "ROW_COUNT"
FROM EXA_STATISTICS.EXA_SQL_LAST_DAY
ORDER BY "START_TIME" DESC
