"""Hosted Dash → Exasol helpers (auto-generated by app_create_exasol_dashboard).

Pyexasol placeholder syntax (use this, not :name):

    queries/example.sql:
        SELECT region, SUM(revenue) AS REV
        FROM SALES
        WHERE order_ts >= ADD_DAYS(CURRENT_TIMESTAMP, -{days!d})
          AND region = {region!s}
        GROUP BY region

    params={"days": 30, "region": "EMEA"}

Placeholder cheat sheet (see dash://exasol/help/sql-placeholders for full table):

    {x!s}  -> 'string'        empty string substitutes to SQL NULL
    {x!d}  -> 1234            validated integer/decimal, unquoted
    {x!f}  -> 1.23            validated float, unquoted
    {x!i}  -> SALES           safe identifier
    {x!q}  -> "DAY"           quoted identifier (use for reserved words)
    {x!r}  -> verbatim        raw SQL fragment - never with user input

Return-contract guarantee:

    `load_rows` / `load_row` / `query_rows` / `query_one` NEVER raise on
    data-layer failure. On error they return a single-row envelope
    `[{"_error": "<message>"}]` (or that dict from `load_row`). Use the
    `has_error` helper below before iterating:

        rows = load_rows(server, metadata, __file__, "queries/x.sql")
        if has_error(rows):
            return render_error_panel(rows[0]["_error"])
        # rows is safe to iterate
"""
from pathlib import Path

from dash import html

from dash_server.exasol.runtime import query_one, query_rows, query_scalar
from dash_server.exasol.runtime import has_error as _runtime_has_error


def has_error(rows):
    """Detect the `[{"_error": "..."}]` envelope every helper returns on failure."""

    return _runtime_has_error(rows)


def load_rows(server, metadata, current_file, sql_relative_path, *, params=None):
    return query_rows(
        server,
        metadata,
        base_dir=str(Path(current_file).resolve().parent),
        sql_relative_path=sql_relative_path,
        params=params or {},
    )


def load_row(server, metadata, current_file, sql_relative_path, *, params=None):
    return query_one(
        server,
        metadata,
        base_dir=str(Path(current_file).resolve().parent),
        sql_relative_path=sql_relative_path,
        params=params or {},
    )


def load_scalar(server, metadata, current_file, sql_relative_path, *, column=None, params=None):
    return query_scalar(
        server,
        metadata,
        base_dir=str(Path(current_file).resolve().parent),
        sql_relative_path=sql_relative_path,
        params=params or {},
        column=column,
    )


def render_error_panel(message):
    return html.Div(
        [
            html.Strong("Exasol query failed"),
            html.Pre(message or "Unknown Exasol error"),
        ],
        style={"backgroundColor": "#fff7ed", "border": "1px solid #fdba74", "padding": "1rem"},
    )


def render_table(rows):
    if not rows:
        return html.Div("No rows returned.", style={"color": "#94a3b8"})
    if rows and rows[0].get("_error"):
        return render_error_panel(rows[0]["_error"])

    columns = list(rows[0].keys())
    return html.Table(
        [
            html.Thead(html.Tr([html.Th(column) for column in columns])),
            html.Tbody(
                [
                    html.Tr([html.Td(str(row.get(column, ""))) for column in columns])
                    for row in rows
                ]
            ),
        ],
        style={"borderCollapse": "collapse", "width": "100%"},
    )
