WITH FILTERED AS (
  SELECT *
  FROM "STARTER_KIT"."CHURN_SCORES"
  WHERE ({contract_all!d} = 1 OR "Contract" IN ({contract!s}))
    AND ({high_risk_only!d} = 0 OR "CHURN_PROBABILITY" >= 0.5)
),
BUCKETED AS (
  SELECT LEAST(FLOOR("CHURN_PROBABILITY" * 10), 9) AS "BUCKET"
  FROM FILTERED
)
SELECT
    CAST("BUCKET" * 10 AS VARCHAR(10)) || '-' || CAST("BUCKET" * 10 + 10 AS VARCHAR(10)) || '%' AS "LABEL",
    CAST(COUNT(*) AS DOUBLE) AS "VALUE",
    "BUCKET" AS "SORT_ORDER"
FROM BUCKETED
GROUP BY "BUCKET"
ORDER BY "BUCKET"
