WITH FILTERED AS (
  SELECT *
  FROM "STARTER_KIT"."CHURN_SCORES"
  WHERE ({contract_all!d} = 1 OR "Contract" IN ({contract!s}))
    AND ({high_risk_only!d} = 0 OR "CHURN_PROBABILITY" >= 0.5)
)
SELECT
    COUNT(*) AS "CUST_COUNT",
    (SELECT COUNT(*) FROM "STARTER_KIT"."CHURN_SCORES") AS "TOTAL_CUSTS",
    SUM(CASE WHEN "CHURN_PROBABILITY" >= 0.5 THEN 1 ELSE 0 END) AS "HIGH_RISK_COUNT",
    COUNT(DISTINCT "Contract") AS "CONTRACT_COUNT",
    CAST(AVG("CHURN_PROBABILITY") * 100 AS DOUBLE) AS "AVG_PREDICTED_RISK_PCT",
    CAST(100.0 * SUM(CASE WHEN "Churn" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) AS DOUBLE) AS "ACTUAL_CHURN_RATE_PCT"
FROM FILTERED
