SELECT TO_CHAR("MEASURE_TIME", 'HH24:MI') AS "T",
       CAST("CPU" AS DOUBLE) AS "CPU",
       CAST("LOAD" AS DOUBLE) AS "LOAD",
       CAST("TEMP_DB_RAM" AS DOUBLE) AS "RAM"
FROM EXA_STATISTICS.EXA_MONITOR_LAST_DAY
WHERE "MEASURE_TIME" >= ADD_HOURS(NOW(), -8)
ORDER BY "MEASURE_TIME"
