SELECT TO_CHAR("MEASURE_TIME", 'HH24:MI') AS "T",
       CAST("USERS" AS INTEGER) AS "USERS",
       CAST("QUERIES" AS INTEGER) AS "QUERIES"
FROM EXA_STATISTICS.EXA_USAGE_LAST_DAY
WHERE "MEASURE_TIME" >= ADD_HOURS(NOW(), -8)
ORDER BY "MEASURE_TIME"
