WITH BASE AS (
  SELECT
    CASE
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%SILVER%' THEN 'Silver'
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%GOLD%' THEN 'Gold'
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%G-SEC%' OR UPPER("UNDERLYING ASSET ") LIKE '%GILT%' OR UPPER("UNDERLYING ASSET ") LIKE '%LIQUID%' OR UPPER("UNDERLYING ASSET ") LIKE '%1D RATE%' OR UPPER("UNDERLYING ASSET ") LIKE '%OVERNIGHT%' OR UPPER("UNDERLYING ASSET ") LIKE '%BHARAT BOND%' OR UPPER("UNDERLYING ASSET ") LIKE '%GOVERNMENT SECURITIES%' THEN 'Debt / Liquid'
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%NASDAQ%' OR UPPER("UNDERLYING ASSET ") LIKE '%HANG SENG%' OR UPPER("UNDERLYING ASSET ") LIKE '%FANG%' OR UPPER("UNDERLYING ASSET ") LIKE '%S&P 500%' OR UPPER("UNDERLYING ASSET ") LIKE '%NYSE%' THEN 'International Equity'
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%NIFTY 50%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY50%' OR UPPER("UNDERLYING ASSET ") LIKE '%SENSEX%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY NEXT 50%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY 100%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY100%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY 200%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY200%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY 500%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY500%' OR UPPER("UNDERLYING ASSET ") LIKE '%MSCI INDIA%' OR UPPER("UNDERLYING ASSET ") LIKE '%TOTAL MARKET%' OR UPPER("UNDERLYING ASSET ") LIKE '%LARGEMIDCAP%' OR UPPER("UNDERLYING ASSET ") LIKE '%MULTICAP%' THEN 'Broad Market Equity'
        ELSE 'Sectoral / Thematic Equity'
    END AS "CATEGORY"
  FROM "STARTER_KIT"."MW_ETF_05_AUG_2026"
)
SELECT DISTINCT "CATEGORY" AS "VALUE" FROM BASE ORDER BY 1
