WITH BASE AS (
  SELECT
    "SYMBOL",
    CASE
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%SILVER%' THEN 'Silver'
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%GOLD%' THEN 'Gold'
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%G-SEC%' OR UPPER("UNDERLYING ASSET ") LIKE '%GILT%' OR UPPER("UNDERLYING ASSET ") LIKE '%LIQUID%' OR UPPER("UNDERLYING ASSET ") LIKE '%1D RATE%' OR UPPER("UNDERLYING ASSET ") LIKE '%OVERNIGHT%' OR UPPER("UNDERLYING ASSET ") LIKE '%BHARAT BOND%' OR UPPER("UNDERLYING ASSET ") LIKE '%GOVERNMENT SECURITIES%' THEN 'Debt / Liquid'
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%NASDAQ%' OR UPPER("UNDERLYING ASSET ") LIKE '%HANG SENG%' OR UPPER("UNDERLYING ASSET ") LIKE '%FANG%' OR UPPER("UNDERLYING ASSET ") LIKE '%S&P 500%' OR UPPER("UNDERLYING ASSET ") LIKE '%NYSE%' THEN 'International Equity'
        WHEN UPPER("UNDERLYING ASSET ") LIKE '%NIFTY 50%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY50%' OR UPPER("UNDERLYING ASSET ") LIKE '%SENSEX%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY NEXT 50%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY 100%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY100%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY 200%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY200%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY 500%' OR UPPER("UNDERLYING ASSET ") LIKE '%NIFTY500%' OR UPPER("UNDERLYING ASSET ") LIKE '%MSCI INDIA%' OR UPPER("UNDERLYING ASSET ") LIKE '%TOTAL MARKET%' OR UPPER("UNDERLYING ASSET ") LIKE '%LARGEMIDCAP%' OR UPPER("UNDERLYING ASSET ") LIKE '%MULTICAP%' THEN 'Broad Market Equity'
        ELSE 'Sectoral / Thematic Equity'
    END AS "CATEGORY",
    "365 D %CHNG" AS "RET_365D",
    CAST(NULLIF(REPLACE("LTP", ',', ''), '-') AS DOUBLE) AS "LTP_NUM",
    CAST(NULLIF(REPLACE("NAV", ',', ''), '-') AS DOUBLE) AS "NAV_NUM",
    CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE) AS "VALUE_CR"
  FROM "STARTER_KIT"."MW_ETF_05_AUG_2026"
),
FILTERED AS (
  SELECT * FROM BASE
  WHERE "LTP_NUM" IS NOT NULL AND "NAV_NUM" IS NOT NULL AND "VALUE_CR" IS NOT NULL
    AND ({category_all!d} = 1 OR "CATEGORY" IN ({category!s}))
    AND ({liquid_only!d} = 0 OR "VALUE_CR" >= 1.0)
),
RANKED AS (
  SELECT
    "SYMBOL", "CATEGORY", CAST("RET_365D" AS DOUBLE) AS "VALUE",
    ROW_NUMBER() OVER (ORDER BY "RET_365D" DESC) AS "RN_TOP",
    ROW_NUMBER() OVER (ORDER BY "RET_365D" ASC) AS "RN_BOTTOM"
  FROM FILTERED
)
SELECT "SYMBOL" AS "LABEL", "VALUE", "CATEGORY" FROM RANKED WHERE "RN_TOP" <= 5
UNION ALL
SELECT "SYMBOL" AS "LABEL", "VALUE", "CATEGORY" FROM RANKED WHERE "RN_BOTTOM" <= 5
ORDER BY "VALUE" DESC
