SELECT CAST("SYMBOL" AS VARCHAR(128)) AS "LABEL",
       CAST(SUM("CHANGE") AS DOUBLE) AS "VALUE"
FROM "STARTER_KIT"."MW_ETF_05_AUG_2026"
WHERE "SYMBOL" IS NOT NULL
GROUP BY 1
ORDER BY 2 DESC
LIMIT 15
