SELECT 'Department' AS "DIMENSION", "Department" AS "VALUE"
FROM "STARTER_KIT"."STUDENTS_PERFORMANCE_DATASET_CLEAN"
GROUP BY "Department"
UNION ALL
SELECT 'Gender' AS "DIMENSION", "Gender" AS "VALUE"
FROM "STARTER_KIT"."STUDENTS_PERFORMANCE_DATASET_CLEAN"
GROUP BY "Gender"
UNION ALL
SELECT 'Family_Income_Level' AS "DIMENSION", "Family_Income_Level" AS "VALUE"
FROM "STARTER_KIT"."STUDENTS_PERFORMANCE_DATASET_CLEAN"
GROUP BY "Family_Income_Level"
UNION ALL
SELECT 'Extracurricular_Activities' AS "DIMENSION", "Extracurricular_Activities" AS "VALUE"
FROM "STARTER_KIT"."STUDENTS_PERFORMANCE_DATASET_CLEAN"
GROUP BY "Extracurricular_Activities"
ORDER BY 1, 2
