SELECT CAST("First_Name" AS VARCHAR(128)) AS "LABEL",
       CAST(SUM("Age") AS DOUBLE) AS "VALUE"
FROM "STARTER_KIT"."STUDENTS_PERFORMANCE_DATASET_CLEAN"
WHERE "First_Name" IS NOT NULL
GROUP BY 1
ORDER BY 2 DESC
LIMIT 15
