WITH SALES AS (
  SELECT
    o."O_ORDERKEY" AS "ORDER_KEY",
    o."O_ORDERSTATUS" AS "STATUS",
    EXTRACT(YEAR FROM o."O_ORDERDATE") AS "YEAR",
    c."C_MKTSEGMENT" AS "SEGMENT",
    r."R_NAME" AS "REGION",
    n."N_NAME" AS "COUNTRY",
    l."L_EXTENDEDPRICE" * (1 - l."L_DISCOUNT") AS "REVENUE"
  FROM "TPCH"."LINEITEM" l
  JOIN "TPCH"."ORDERS" o ON l."L_ORDERKEY" = o."O_ORDERKEY"
  JOIN "TPCH"."CUSTOMER" c ON o."O_CUSTKEY" = c."C_CUSTKEY"
  JOIN "TPCH"."NATION" n ON c."C_NATIONKEY" = n."N_NATIONKEY"
  JOIN "TPCH"."REGION" r ON n."N_REGIONKEY" = r."R_REGIONKEY"
),
FILTERED AS (
  SELECT * FROM SALES
  WHERE ({region_all!d} = 1 OR "REGION" IN ({region!s}))
    AND ({segment_all!d} = 1 OR "SEGMENT" IN ({segment!s}))
    AND ({status_all!d} = 1 OR "STATUS" IN ({status!s}))
    AND "YEAR" BETWEEN {year_min!d} AND {year_max!d}
)
SELECT "COUNTRY" AS "LABEL", CAST(SUM("REVENUE") AS DOUBLE) AS "VALUE"
FROM FILTERED
GROUP BY "COUNTRY"
ORDER BY "VALUE" DESC
LIMIT 10
