WITH ALL_STOCKS AS (
  SELECT 'Nifty 50' AS "SEGMENT", "SYMBOL", "365 D %CHNG" AS "RET_1Y", "30 D %CHNG" AS "RET_30D",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE) AS "TURNOVER_CR"
  FROM "STARTER_KIT"."MW_NIFTY_50_04_AUG_2026" WHERE "SYMBOL" != 'NIFTY 50'
  UNION ALL
  SELECT 'Nifty Bank', "SYMBOL", "365 D %CHNG", "30 D %CHNG",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE)
  FROM "STARTER_KIT"."MW_NIFTY_BANK_04_AUG_2026" WHERE "SYMBOL" != 'NIFTY BANK'
  UNION ALL
  SELECT 'Nifty Financial Services', "SYMBOL", "365 D %CHNG", "30 D %CHNG",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE)
  FROM "STARTER_KIT"."MW_NIFTY_FINANCIAL_SERVICES_04_AUG_2026" WHERE "SYMBOL" != 'NIFTY FINANCIAL SERVICES'
  UNION ALL
  SELECT 'Nifty Midcap Select', "SYMBOL", "365 D %CHNG", "30 D %CHNG",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE)
  FROM "STARTER_KIT"."MW_NIFTY_MIDCAP_SELECT_04_AUG_2026" WHERE "SYMBOL" != 'NIFTY MIDCAP SELECT'
  UNION ALL
  SELECT 'Nifty Next 50', "SYMBOL", "365 D %CHNG", "30 D %CHNG",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE)
  FROM "STARTER_KIT"."MW_NIFTY_NEXT_50_04_AUG_2026" WHERE "SYMBOL" != 'NIFTY NEXT 50'
),
FILTERED AS (
  SELECT * FROM ALL_STOCKS
  WHERE ({segment_all!d} = 1 OR "SEGMENT" IN ({segment!s}))
),
DEDUPED AS (
  SELECT "SEGMENT", "SYMBOL", "RET_1Y", "RET_30D", "TURNOVER_CR",
    ROW_NUMBER() OVER (PARTITION BY "SYMBOL" ORDER BY "SEGMENT") AS "RN"
  FROM FILTERED
)
SELECT "SEGMENT", "SYMBOL", "RET_1Y", "RET_30D", "TURNOVER_CR"
FROM DEDUPED
WHERE "RN" = 1
