WITH SEGMENTS AS (
  SELECT 'Nifty 50' AS "SEGMENT", "LTP", "365 D %CHNG" AS "RET_1Y", "30 D %CHNG" AS "RET_30D",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE) AS "TURNOVER_CR"
  FROM "STARTER_KIT"."MW_NIFTY_50_04_AUG_2026" WHERE "SYMBOL" = 'NIFTY 50'
  UNION ALL
  SELECT 'Nifty Bank', "LTP", "365 D %CHNG", "30 D %CHNG",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE)
  FROM "STARTER_KIT"."MW_NIFTY_BANK_04_AUG_2026" WHERE "SYMBOL" = 'NIFTY BANK'
  UNION ALL
  SELECT 'Nifty Financial Services', "LTP", "365 D %CHNG", "30 D %CHNG",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE)
  FROM "STARTER_KIT"."MW_NIFTY_FINANCIAL_SERVICES_04_AUG_2026" WHERE "SYMBOL" = 'NIFTY FINANCIAL SERVICES'
  UNION ALL
  SELECT 'Nifty Midcap Select', "LTP", "365 D %CHNG", "30 D %CHNG",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE)
  FROM "STARTER_KIT"."MW_NIFTY_MIDCAP_SELECT_04_AUG_2026" WHERE "SYMBOL" = 'NIFTY MIDCAP SELECT'
  UNION ALL
  SELECT 'Nifty Next 50', "LTP", "365 D %CHNG", "30 D %CHNG",
         CAST(NULLIF(REPLACE("VALUE (Crores)", ',', ''), '-') AS DOUBLE)
  FROM "STARTER_KIT"."MW_NIFTY_NEXT_50_04_AUG_2026" WHERE "SYMBOL" = 'NIFTY NEXT 50'
)
SELECT
    "SEGMENT",
    CAST(NULLIF(REPLACE("LTP", ',', ''), '-') AS DOUBLE) AS "LTP_NUM",
    "RET_1Y",
    "RET_30D",
    "TURNOVER_CR"
FROM SEGMENTS
WHERE ({segment_all!d} = 1 OR "SEGMENT" IN ({segment!s}))
ORDER BY "TURNOVER_CR" DESC
